### ISSUE TITLE
如何修改用户名及其邮箱

### ISSUE THREAD

**Issue by heycyril** [zengchw/leanote#1]
如何修改用户名及其邮箱，没有找到相应的位置，点击邮件那里，
Email
Your current email is: admin@leanote.com 
Unverfied Verify now or Resend verification email

点击后跳到 mail.leanote.com

**Comment by axboy** [comment]
才看到消息。
刚刚试了试，在界面上没试出来，确实没有修改邮箱的，然后就进入容器，试着直接改数据库，改完发现是可以的，参考命令如下。
```sh
root@192.168.1.10:~# docker exec -it leanote bash
root@5cbaeb78cbf4:/# mongo
> use leanote;
> db.users.update({"Email" : "admin@leanote.com"},{$set :{"Email":"admin@test.com"  } }); 
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 1 })
```

**Comment by Extremenne** [comment]
但是改完后只有网页发生了变化，还是收不到邮件。

**Comment by axboy** [comment]
> 但是改完后只有网页发生了变化，还是收不到邮件。

检查一下服务器、网络、邮箱配置
https://github.com/leanote/leanote/issues/853

**Comment by npc-wake** [comment]
但是改完后只有网页发生了变化，还是收不到邮件。

检查一下服务器、网络、邮箱配置
https://github.com/leanote/leanote/issues/853    👈该网页显示404
