### ISSUE TITLE
nginx配置和mongo找不到入口

### ISSUE THREAD

**Issue by ghostxiu** [zengchw/leanote#11]
使用
`docker exec -i -t  leanote      /bin/sh -c /bin/bash /root/run.sh`
进入容器，找不到nginx服务,mongo命令运行无效
求教一下要怎么进入容器并配置

**Comment by axboy** [comment]
1、容器内只有mongodb、leanote，没有nginx
2、进入容器命令如下，然后就当做一个精简的ubuntu系统来用
```sh
docker exec -it leanote bash    # 进入容器
ps -ef          # 进容器后，查看容器内进程
ls -al /data    # 进容器后，列出/data目录
```
3、容器只是起一个服务，暴露9000端口，其它东西建议容器外处理
4、没特殊需要，不要进容器直接操作，除非你清楚你在做什么

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu

**Comment by ghostxiu** [comment]
多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 下午5:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [axboy/docker-leanote] nginx配置和mongo找不到入口 (Issue #11)





 
1、容器内只有mongodb、leanote，没有nginx
 2、进入容器命令如下，然后就当做一个精简的ubuntu系统来用
 docker exec -it leanote bash    # 进入容器 ps -ef          # 进容器后，查看容器内进程 ls -al /data    # 进容器后，列出/data目录
 
3、容器只是起一个服务，暴露9000端口，其它东西建议容器外处理
 4、没特殊需要，不要进容器直接操作，除非你清楚你在做什么

**Comment by ghostxiu** [comment]
你好！您的邮件已收到，处理成功后会与您联系。修ghostxiu
