### ISSUE TITLE
Web端Note路径下的搜索功能无法使用

### ISSUE THREAD

**Issue by emengweb** [zengchw/leanote#14]
在登录后的文章管理界面，搜索以及点击标签进行搜索功能都不可用。
点击后界面会卡Loading，查看了下搜索路径返回的是空白页，希望可以修复下。

PS.在博客端的搜索功能使用正常

**Comment by axboy** [comment]
刚试了下，在 **/note** 页面，搜索笔记和搜索标签，我这里都正常，为方便排错可加**qq: 1123300322**，回复及时些。

不过搜索标签有个问题是，不能直接点那几个默认出来的标签(红色、蓝色等)，自己打字生成的标签可以搜索，那几个颜色不行。

一直loading，检查一下 **/note/searchNoteByTags** 和 **/note/searchNote** 这两个接口，网络有没有拦截，比如nginx。

**Comment by emengweb** [comment]
十分感谢，我稍后再详细拍查下是否被拦截

外地臭打工的 ***@***.***> 于 2022年10月17日周一 14:34写道：

**Comment by emengweb** [comment]
Nginx返回的是404，日志：
```
127.0.0.1 - - [18/Oct/2022:12:26:34 +0800] ＂POST /note/searchNote HTTP/1.1＂ 404 740 ＂https://xxx.com/note/634e0565c4d9ea59ff000000＂ ＂Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36＂
```
看起来是路径没有被识别到，不知道什么原因会导致这种情况呢？

**Comment by emengweb** [comment]
解决了！十分感谢！
