### ISSUE TITLE
一访问就挂掉了

### ISSUE THREAD

**Issue by songofhawk** [zengchw/leanote#2]
docker容器可以启动, 文件夹也映射成功了, 但是浏览器一访问: localhost:9000, docker容器就挂掉了, 从constainer log里看, 最后的输出是这样的:
![image](https://user-images.githubusercontent.com/2861016/56628704-5e447280-667d-11e9-888d-f61f7cea2b31.png)

请问可能是什么原因呢?

**Comment by axboy** [comment]
首先抱歉，才看到这个消息，最近几个月没怎么看github。
然后启动错误是我最后一次提交的run.sh有问题，最近没看也就不知道没修复，latest版本的镜像bug，尽快修复，可以先用2.6.1版本
