### ISSUE TITLE
如何导入以前的数据呢

### ISSUE THREAD

**Issue by xuze1993** [zengchw/leanote#3]
内置数据库版，没注意持久化
今天看了下容器内/data/db内是有数据的，不过好像无法导入啊。。

**Comment by xuze1993** [comment]
/data/db好像是expose了
重新dump一份导入可以用了，为什么直接mongod --dbpath /leanote/data  不行呢。。

**Comment by axboy** [comment]
```
docker cp leanote:/data/db YOUR_PATH
```
把容器内的数据拷出来，新起容器重新挂载

**Comment by pblh123** [comment]
推荐通过单独运行mongdb数据库，来进行数据存储。这样导入数据问题是不是就可以解决。我遇到的问题时无法备份数据 备份数据时报错 exit status 127

**Comment by jzhjm** [comment]
> ```
> docker cp leanote:/data/db YOUR_PATH
> ```
> 
> 把容器内的数据拷出来，新起容器重新挂载

1. 为什么我使用内置数据库版本，客户端（测试了Windows和 iOS）无法同步数据，不内置数据库版本就正常，但是不内置数据库版本 无法使用 网页后台的备份功能(报错:exit status 127，应该是没有mongodump 和 mongorestore 的原因)
2. 如果使用内置数据库版本 连接 独立运行的 mongo 数据库，就能正常同步，但是 网页后台的备份功能将失效(报错:exit status 1)

**Comment by axboy** [comment]
> > ```
> > docker cp leanote:/data/db YOUR_PATH
> > ```
> > 
> > 
> > 把容器内的数据拷出来，新起容器重新挂载
> 
> 1. 为什么我使用内置数据库版本，客户端（测试了Windows和 iOS）无法同步数据，不内置数据库版本就正常，但是不内置数据库版本 无法使用 网页后台的备份功能(报错:exit status 127，应该是没有mongodump 和 mongorestore 的原因)
> 2. 如果使用内置数据库版本 连接 独立运行的 mongo 数据库，就能正常同步，但是 网页后台的备份功能将失效(报错:exit status 1)
---

**Comment by axboy** [comment]
> > ```
> > docker cp leanote:/data/db YOUR_PATH
> > ```
> > 
> > 
> > 把容器内的数据拷出来，新起容器重新挂载
> 
> 1. 为什么我使用内置数据库版本，客户端（测试了Windows和 iOS）无法同步数据，不内置数据库版本就正常，但是不内置数据库版本 无法使用 网页后台的备份功能(报错:exit status 127，应该是没有mongodump 和 mongorestore 的原因)
> 2. 如果使用内置数据库版本 连接 独立运行的 mongo 数据库，就能正常同步，但是 网页后台的备份功能将失效(报错:exit status 1)

---

内置数据库的，我这边备份是备份容器的文件，迁移直接新启容器就好了，内置免密数据库2.6.1版的多端同步我这可以同步数据。如果备份数据库，那也不用映射文件了。

网页后台admin的备份要mongodump和mongorestore命令

**Comment by jzhjm** [comment]
> > > ```
> > > docker cp leanote:/data/db YOUR_PATH
> > > ```
> > > 
> > > 
> > > 把容器内的数据拷出来，新起容器重新挂载
> > 
> > 
> > 
> > 1. 为什么我使用内置数据库版本，客户端（测试了Windows和 iOS）无法同步数据，不内置数据库版本就正常，但是不内置数据库版本 无法使用 网页后台的备份功能(报错:exit status 127，应该是没有mongodump 和 mongorestore 的原因)
> > 2. 如果使用内置数据库版本 连接 独立运行的 mongo 数据库，就能正常同步，但是 网页后台的备份功能将失效(报错:exit status 1)
> 
> 内置数据库的，我这边备份是备份容器的文件，迁移直接新启容器就好了，内置免密数据库2.6.1版的多端同步我这可以同步数据。如果备份数据库，那也不用映射文件了。
> 
> 网页后台admin的备份要mongodump和mongorestore命令

我之前使用的是latest版本，只要在Web端修改了数据，Windows客户端同步就会出现问题，改用2.6.1版本就没有这样的问题

**Comment by axboy** [comment]
> 我之前使用的是latest版本，只要在Web端修改了数据，Windows客户端同步就会出现问题，改用2.6.1版本就没有这样的问题

latest版本有半年时间和2.6.1不同步，当时更新后的latest版本有问题，这是我的锅，优化出新bug。

**Comment by axboy** [comment]
nodb版网页后台备份数据库和导出pdf功能已增加
