### ISSUE TITLE
wkhtmltox能否内置一下

### ISSUE THREAD

**Issue by RayYe586** [zengchw/leanote#4]

**Comment by axboy** [comment]
wkhtmltox不太熟，而且笔记可以导出pdf

**Comment by jzhjm** [comment]
> wkhtmltox不太熟，而且笔记可以导出pdf

作者是想说 客户端可以导出PDF吧

**Comment by axboy** [comment]
> > wkhtmltox不太熟，而且笔记可以导出pdf
> 
> 作者是想说 客户端可以导出PDF吧

对，我也才发现网页版的导出不可用，一直用的客户端。

其实吧，我看leantoe仓库都很久没更新了，我这个还是依赖leanote的，最初我也只是放一起方便自己使用，没想到还有这么多用户

**Comment by jzhjm** [comment]
> > > wkhtmltox不太熟，而且笔记可以导出pdf
> > 
> > 
> > 作者是想说 客户端可以导出PDF吧
> 
> 对，我也才发现网页版的导出不可用，一直用的客户端。
> 
> 其实吧，我看leantoe仓库都很久没更新了，我这个还是依赖leanote的，最初我也只是放一起方便自己使用，没想到还有这么多用户

我在镜像里面安装了 wkhtmltopdf 也不能使用网页版的 导出PDF，直接在容器内 `apt install wkhtmltopdf`，`jim3ma/leanote` 这个镜像是可以使用网页版导出 PDF的，搞不明白

**Comment by axboy** [comment]
> 我在镜像里面安装了 wkhtmltopdf 也不能使用网页版的 导出PDF，直接在容器内 `apt install wkhtmltopdf`，`jim3ma/leanote` 这个镜像是可以使用网页版导出 PDF的，搞不明白

---

刚测试了一下，装了wkhtmltopdf，还缺一些字体，我尽快弄一下

**Comment by axboy** [comment]
> 我在镜像里面安装了 wkhtmltopdf 也不能使用网页版的 导出PDF，直接在容器内 `apt install wkhtmltopdf`，`jim3ma/leanote` 这个镜像是可以使用网页版导出 PDF的，搞不明白

我用`jim3ma/leanote:latest`这个镜像也未能导出pdf，而且根据控制台的输出
```
/usr/local/bin/wkhtmltopdf --lowquality --window-status done "http://localhost:9000/note/toPdf?noteId=5483207cf4e87203a4000001&appKey=V85ZzBeTnzpsHyjQX4zukbQ8qqtju9y2aDM55VWxAH9Qop19poekx3xkcDVvr000"  "/leanote/bin/src/github.com/leanote/leanote/files/export_pdf/48a56f0a9f732271a6dff22da544158e.pdf"
```
jim3ma的wkhtmltopdf命令不在/usr/local/bin/目录中，我好奇怎么导出成功的

目前我仓库中的dockerfile已更新，暂未构建镜像到dockerhub，注意更新了mongodb版本，和旧版本不兼容，安装了wkhtmltopdf，但浏览器暂不可用，通过进入容器执行上述命令可以生成文件，没搞明白

**Comment by jzhjm** [comment]
> > 我在镜像里面安装了 wkhtmltopdf 也不能使用网页版的 导出PDF，直接在容器内 `apt install wkhtmltopdf`，`jim3ma/leanote` 这个镜像是可以使用网页版导出 PDF的，搞不明白
> 
> 我用`jim3ma/leanote:latest`这个镜像也未能导出pdf，而且根据控制台的输出
> 
> ```
> /usr/local/bin/wkhtmltopdf --lowquality --window-status done "http://localhost:9000/note/toPdf?noteId=5483207cf4e87203a4000001&appKey=V85ZzBeTnzpsHyjQX4zukbQ8qqtju9y2aDM55VWxAH9Qop19poekx3xkcDVvr000"  "/leanote/bin/src/github.com/leanote/leanote/files/export_pdf/48a56f0a9f732271a6dff22da544158e.pdf"
> ```
> 
> jim3ma的wkhtmltopdf命令不在/usr/local/bin/目录中，我好奇怎么导出成功的
> 
> 目前我仓库中的dockerfile已更新，暂未构建镜像到dockerhub，注意更新了mongodb版本，和旧版本不兼容，安装了wkhtmltopdf，但浏览器暂不可用，通过进入容器执行上述命令可以生成文件，没搞明白

wkhtmltopdf 的默认安装路径是 `/usr/bin/wkhtmltopdf` ，在后台管理设置成 这个路径就可以在网页端转换了，mongodump 和 mongorestore 也是这个路径

**Comment by hzmabin** [comment]
如果导出的问题解决了，方便的话更新下Docker镜像哦，谢谢 。。。

**Comment by axboy** [comment]
> 如果导出的问题解决了，方便的话更新下Docker镜像哦，谢谢 。。。

latest镜像已更新

**Comment by jzhjm** [comment]
ARM 版 可以正常使用吗？

**Comment by axboy** [comment]
> ARM 版 可以正常使用吗？

arm版未更新，网页版暂不支持导出，还是2年前的版本，仅用树莓派3b+(centos7)测试。

**Comment by hzmabin** [comment]
> > 如果导出的问题解决了，方便的话更新下Docker镜像哦，谢谢 。。。
> 
> latest镜像已更新

导出功能非常完美，给你一个大大的赞 ！！！
